### ISSUE TITLE
Next week's content + github as a communication hub

### ISSUE THREAD

**Issue by thomas-coudrat** [ml-bourne/minutes#1]
Hi all, 

Just trying out the issues as a mode of communication. Issues will be attached to repositories. It works in this case to talk about next week's content in the minutes repo! Not sure how it will work out for other communication. Maybe we could have a repo to collect general ML info that we learn about along the way? Alistair you were talking about a way to create a table of content that links to various sections of a document. We could do that and use it as a repository of everything we learn! That would be a constructive thing to build. 

Now about the issue I wanted to raise as a test: @kianho let us know what you wanted to show us next week! 

Cheers

Thomad

**Comment by kianho** [comment]
no worries, I'll probably step through a basic solution to the otto competition, probably including:
- basic exploratory data analysis on the features
  - how are they distributed? how does this impact the classifiers?
- basic training, validation, and testing approaches
- comparing the performance of a few classifiers
  - nuances of binary vs. multi-class classification problems (otto is multi-class)
  - (tentative) statistical comparisons of classifier performance
- tabulating/visualising classifier results
  - especially useful for thesis/peer-reviewed manuscripts

depends on what else comes to my head

also, i will accept requests for topics, be it theoretical or practical issues
